language: python
sudo: required
dist: xenial
python:
  - '3.7'
  - '3.8-dev'
services:
  - mysql
before_install:
  - mysql -e 'CREATE DATABASE sc2monitor;'
install:
  - 'pip install -e .'
script:
  - 'pytest --apikey=$apikey --apisecret=$apisecret'
deploy:
  provider: pypi
  user: "pressure"
  distributions: "sdist bdist_wheel"
  password: "$pypi"
  skip_existing: true
  on:
    tags: true
