language: python
sudo: required
dist: xenial
python:
- 3.7
install:
- pip install -e .
env:
  secure: qeVO1jVWTplxnp2jHdNOCqjtWTnGIpD8/bkKHsqHki9HH0BsNl7AmNIYWQ97W+QVJmrAQFOe1HvOt/NlZ0oAfcI1jcc41zHxHDYNgUNRCQJdL7f1w+AllBrQB72rtsYHyJg8spOf5Z5XJg9qj3Ed0Y288Dzpz7YnoCeJ3gRsSILAUtF/DhQOnVe4Xpp1fRZtbV7eku+BABwiqMXfSTtXaisrTmDumgbY0y9yqYMhQHZ4FTaCm0HC4vnCV07XwIJWhDOgiC13wWeYpyNLBZ6EkzC2U8DTvlPiFselKNQwyQB7+ZR9yeHs0sN+tCV93657f1+eLE1Co52gQWZdO0czn6fJfDpgknxMuKZt8XRJSPly5tUIs8gOlzXl4ds2D60AgyGT1rYrAJVOLPssGihsmmnnUBBNOMh2UQpIECpMdqdQOXUUCToBB8nmRomaOi3iQlM0K9T2v8kLYSzkX15IJklYzco5gGXDACqnCK9S47A28xaThExcjaOlcKn7v3jakQKQGMt+lRLl+PGOG5QXkU0fH4shV+HoaRdndXsuspr7GydHU/dYDbWtM+e4Al39OOUIRTol6Q7IRa4Fj/b5bkJziIUg6t0IpKyqTmdQvNkIMCBCtAXKFtHgGpMZIbuXFv76gRVn2QnE5VNta8F56k69dvtykSRtTFwuMAO2eOA=
script:
- pytest --cmdopt=$CMDOPT
