language: python
sudo: required
dist: xenial
python:
  - '3.7'
install:
  - 'pip install -e .'
env:
  global:
    - secure: do4ciARbpDk0awH9IOJJb44wAYyJAgq2fXLXW70R9qMjQCUwiK1pRay771e9g7bXfCzVoK/q9lMQDs1hJfsJq+dcwCrlLWg87Fz8kuK/L6W/zWOgekdutd1kS6Ak3j3AnLtppUy0QinPK5f+YORjhBtID1I4pMIPV/np0LBRZxQEkVz3yVpGXrIZ+hyDdgo/UVSM2AO2Pl3L2s4jLKMuM5apEWtZC9/BAilr4u2alIF6p9o2+2+N03zFc2YzmcLv+TKm19mZbqqumbaPU8ZHJUsFZ/qgqJZveB9Odh7NPKqpjIUClknRDyl9P8+bQ1wqJCMuBj0q07jG34FHCILAMLMr2iE62GyXi7Q1ycXAcNL83puIfLdWFXhBAPt7vgi3xgqGZlp+WyHKIhYI2LFLZTXGHemkAlv+yvBHAz82qQk6KL6vv+o3rzfEe8mgeKOLqoQpRp0TRZwINfWvEaamdo2p33CA1/w+T5qWOP/PF7YbFLXBRuklYSHpbuxXGUXHV2vb0zKsO4LOoVF2vpEEFK1+NvnbspOiRVVaIQvvuaq8rJvCWI/pgCI1XOWXdwFm1DIo9sYVxhHLWsNXTokgvtdTLY1QI/Hj82+0BKuSlgzv/7fBjBu/hQRiOSRFiqVEnwWnLk1pKboDDlmPrS9xY1o3B3MvQ3oE700uAyAbQHw=
script:
  - 'pytest --cmdopt=$CMDOPT'
