language: python
sudo: required
dist: xenial
python:
  - '3.7'
install:
  - 'pip install -e .'
env:
  global:
    - secure: 'eVYxm1giNnSvE6EYWf2d/Cm3KoLu5UdLfy49JR2Ocu1S1cV+BdlI/RHJ6ig+OwGHD2xPVx63Sbib5V8cwjK9Xup6Sda0AdFhXEFPfvK3vvFoz8ZrR58Vba7kuMOfL+A1kg75X/5vTraICeyEb2OSBZsrueXTtAz9EPxfsycbEd92+f2sQMJPzX1s+z/7Tv9zy2ZRjhmJR6SqbMGbFHrRoeSMetNyeo79RPYTDmv8CqiYfhi/r9EC3KIxPIWcYYOGbUpWKnpBy1c+49hUFTJ8Yh7iD4IYVKUaCUkLyv91Lx7xl63RlDlUAvYQnOH0LDcAXv7DZaKQ20tTGw1sK6m7lyJdXXiLQF0cfO1yH8Oc8BF+ATa2L7VCQNUp+37AEao5bgOQfYiDuOYvxxikvbtE9V/TMWno1+baDJdoCxmTiPTF+l45yvlCnWwKJF4FumZJXrtaQ+C5z2Id5Yc2zjj1rxfxS4p9zjg8PQHtlTRt5vYf5gbG9mRcuslxUHGcoH8L2OfRuR8CIVjc3uLZR3TOlipbS4hJC2tFJh3yvwUivJmvt6vaBhUkR4jgCN3KCdMLsKq+vDoWm8L8C0/OV7rv2ojFV+ClkgqUhko6fU+5/yGRZEYdbHpXd313npEhedFg8Ef001/qG/Fwi0oU+pBLwpmEe+DUtDKu7U5hF/4Q04c='
script:
  - 'pytest --cmdopt=$CMDOPT'
