language: python
cache: pip
dist: xenial # currently needed for python >=3.7
python:
  - '3.7'
  - '3.8-dev'
addons:
  mariadb: '10.3'
before_install:
  - mysql -e 'CREATE DATABASE sc2monitor;'
install:
  - 'pip install -e .'
script:
  - 'pytest --apikey=$apikey --apisecret=$apisecret'
  - 'pytest --apikey=$apikey --apisecret=$apisecret --protocol=mysql+pymysql --db=127.0.0.1 --user=travis'
deploy:
  provider: pypi
  user: "pressure"
  password: "$pypi"
  skip_existing: true
  on:
    distributions: "sdist bdist_wheel"
    branch: master
    condition: $TRAVIS_PYTHON_VERSION=3.7
