language: python
sudo: required
dist: xenial
python:
- 3.7
install:
- pip install -e .
env:
- secure: lTgIQXHcDzZxp9iD6Pm6JsuuX3Ek71/ODBJUlzHQnL0QobpIrw8FCb93GqmpYXXMiynM9LooAtqe8byFeCNbwsFEd/PZaxIjKSYDALOTwBr1PfZo4/ghPU81Cr6FxLJZJF3Rr02RWbnSRXeJBoSiA0e3ON3AGaTMfDWi4V8OYSfniujvQ7/YLb4HQJiTiIjt7ckLSAHAMGwbTXHJrR2h/XqsayrIPSauFgb6TY72+KMY9fFHjTbBAUIzj2eIGssEEPIRyD0gHMVIzLfJqSt1x4k+RHGWxVPE9uaKe8vavo9vye6TU//C1QeAiUeEhg0N0MHrTmO5r0UhKzJdi7ormbeUySiEQKpX+rZbs4KuPVZiLt8sqNoiFULrtooR2rHHxBgYE3Xj0AUVtwLwx/p0NvmJ9NI0YQamlZHwtTnoV3f3XDuPvBxCO4sjSyrdjSu/4xljrh8yGlmnv+RouNIOrY0Fc5T3m6ArdW89bvxt3zZUOa6mGP9osOFKekkL1RssrppuzzpAYIhERP/FodfRyJk2DGJxFQ0rEfg368ecgmLwC50fKMolL0wqDvYtfxOyA2KX+7otbhz/lQgTkX//Mf+3hYA2cbHNTmWseoN9BZEkJAcVXwqWb9+Ux1HnzisUk7NuHY8mtTZm5Az03xqKg4nxp1TuQO8JtXzw/m7T2X0=
script:
- pytest --cmdopt=$CMDOPT
