language: python
sudo: required
dist: xenial
python:
  - '3.7'
install:
  - 'pip install -e .'
script:
  - 'pytest --cmdopt=$CMDOPT'
deploy:
  provider: pypi
  user: "pressure"
  distributions: "sdist bdist_wheel"
  password: "$pypi"
