language: python
sudo: required
dist: xenial
python:
  - "3.7"
  - "3.8-dev"  # 3.5 development branch
# command to install dependencies
install:
  - pip install -e .
# command to run tests
script:
  - pytest
deploy:
  provider: pypi
  on:
    tags: true
  user: "pressure"
  password:
    secure: bx9OF/UEgrU0z5PFquUTnweLHOMSwS6ZySRJu9um7xCX12pYKLsr6R+FIdIj4hwbJIGnS3SGBj70FYx0uelNRvNklk9hZL+iWjewplQDGPu4xmAfhm6eS30EDls6tPhnPaZU93aHhiNUao54zHnybyTYbRZpRH7bdf+MSRrmKJkpG528LFpDpuYxhj6zVmdOYtk7zebfZDCd14PHFVNRwxQi/KLdx9l8qYWW7SEVA3Hwyt2n/hLFUWMuRuuEzp1qddKq06+vubSw2ZiJctL9abzjZAnpGq5bSnFg6xI/Ybk2PlSD2YOPUfJNsTtqHUgvsq30XUf3Jgj3EMFtpjBKjRV4L1N8YICKqklYKrZyX+zKWGTwvYpfrMh1aYemayXXJwPCksdZscZQLV0H9+dFAYpYKtfIXOZB+WBNXLVJl9JjSWWu0CBP+OCe8LUMVRou7KJCQ28PiYpt6azKv8A7JntyiQpuUfJRr1LMTzHNWRUiXQjEh84kNMLmPpcPvVPJkGnfSiz3FtavZnzO5qDZdPVH3IoId9c64y3jjdU/HiVLP0qFhz9SSvnH1mmxbff21OrDHeMehpBG5Z5rhNa1eXSd/ZcX3NogF9PdwgsuMfJHeFGDAuH/gCaXl3VPUd0mo5KtQnY7WmDazgULrfLcsw267MtSGFllO23VM/JqAT0=
