language: python
sudo: required
dist: xenial
python:
  - "3.7"
  - "3.8-dev"  # 3.5 development branch
# command to install dependencies
install:
  - pip install -e .
# command to run tests
script:
  - pytest
deploy:
  provider: pypi
  on:
    tags: true
  user: "pressure"
  password:
    secure: fvRFZ1E7CZ59NmAlXVKB3O3jb6nhmlRcW+WYGyV4e009RNkDtP4APGorV8+TKkwG0OnFwUSS2gPExlxnSPOMa2g4pe+u4+7v+qWCb02aLK3h72xWxD8MalTIakr8PoElO7xUZSY/jDvoFvHI1lf8QR9nVNgHmTSACyeFaCo1J7qVMfRG+5rZLyzawS1wM60zHus+rLv6cHOXKh8T3HAb/X5mp/YHzgfgp2+vk7TNMP6aEy+eKflNtmppS/Ym/dIhnczCkS0rTlePnUzYVDuxThCzheFgp0fgC0ulHLKdFqgtZzTnLArfZ7kBzGmmjORRw6nt+DUA+j1zEmi69r256fabH/STcI/KG9RcEWnvxIFB6joIvQrIYGHNkF0u9LWVByqlHwGBjMZi+hDvr8rW/dD0KC3rugkKwxTl/sjKipp0ojixAEi3opl3cAOZzQ2u0z7wSnIJRl/0BwaYXi6uKAYxGT5/tG3b2B6g3q3K7Fnc7rrwGA091UPiFpcfluf/hCEMygExZUJom/hIxuNS58hUcXhLwph+WHsUSFhVDjL9C1n9Knwvbceh4C9EFi8oCeE9ZRrzxQfXr+HHcOoLVpJhpA0QeMOpMSMEANnn9TuCC61SIPKeDOpd4MTUv1qPaIhKJz0Ev8/gydt1VZzCHkEm3hDYWAQgkwFvyZXeHJU=
