language: python
sudo: required
dist: xenial
python:
- 3.7
install:
- pip install -e .
env:
  global:
    - secure: qzsXIqkNhS5FiWgMzXDGNlLfvq8VOunMwZmE5WVYjFJs5z0rVnKt7MKceSZm7zzbiQVWSR10SaOzFM5tSqAfYRg+mQyTotj9a+abDjWju7qnFvIrfDk39njIyFl8tLSOPYACyfOzdlxwEfW8xWB9d90TakJK4LxXPTOXtj6ba2cSwGknuesvPJKR1rkqtdV8O5eE0vzdEvc5Fo4McM8OOpVe+aiec86+JMpJyGEIh3toQbh+aty5K9vgWYkQAD6NZCZHbLMsB0bRulzCm14z88UTvnslhmWBtIBeaVMhZsxxfTZS7AU5FWpHF4b2iKAgbBLRF5JApDg7N1oVYEFarEqrtNCtPi61kF3K91w1l1YTmQ6AuSngMN4KXwo6BDvt3XtNCNw9kegWM/Y3vehmOVi3mEpn8Os672noesyj5Kso8n/NC2QfTljioD3xDkPayUQmkM5d3xK1Pyrqr7ysj83rdQ2PxrQSPorF4MEr61RwtzvGHdnl1g1bO3uOiuJd3XJwsoAAJFPrmB3kPJ7VL+JxFsW3XQQ5uh1t4nJDbKbR6AoEGd1/Qz/RJwYyoeup/ygIMl+t679G0mbFyrh7uTjuRabKItNpyM5I8X+153d0TBiB/3u8GXTPVNrK4lfaKXded7OLj/hgeGAzUHTJJ3FkRkMenRAWA3A0WIKX6Nw=
script:
- pytest --cmdopt=$CMDOPT
