language: python
sudo: required
dist: xenial
python:
  - "3.7"
  - "3.8-dev"  # 3.5 development branch
# command to install dependencies
install:
  - pip install -e .
# command to run tests
script:
  - pytest
deploy:
  provider: pypi
  on:
    tags: true
  user: "pressure"
  password:
    secure: ivClS4teg9+cKooABup9Mk7mYNzl7p23GgPTjunRVq2PSFcFJQ4FbDIu8lAde0WfYJNQ698QxwfInYVqxKFbaZwYDXMzWBE5bEynlbvupCjPngXym1bU6VVFw9ymNp4z3GSUuAlem+RYFZ66ph71o+DbcIb26vKmHaAkl8b4WjCMgOB53gWlCCF3inhZgTcXXeGl+otn58Ip69tSH5YC89NDw3XLazjhCv9vBU0lDbktqj9ip048nwN9fMmFrf1jpvn2/eSpU5kx06susIluXUN7Hb/dQtQC7OVHmfWksUNCOhT/takuHYySQn6iJfze+1NHlQfypVc4fYG+mb6/iFZk7q20H+qB6ShZUPsmEZK5Vpf8lR1YtLokuehHRL2Dqveh6OuTY3KJ9OV+EfHk/8FSvXAo/MOe77n5jKJUuq/L9rzc+AL4FQUoe4ZbORibcGPWsgkdZlr3XQQamTJXKiXYcW91orL7oDvTDJt7/09jBUlIhic8ZaOz6eLUZwM3sJQJphTluVPmyc09wFXCqkBQGFYvM3lBlA6oHCVlnGHmaC9n02cqUVPwPaZu20hIZ1vEcHMb8fmEHtl1nEZFrPagpfgmkuUqwkln4+hdVdgFBvk8UTALGrJ1xUD8fheXBet+OqgTdGXwFFfy8pncQyMpnbA0eDHgqrXr/7yNfoc=
