language: python
sudo: required
dist: xenial
python:
- 3.7
install:
- pip install -e .
env:
  secure: K1QGFrRoQebUZ7WHqX5uFWlzennMZgcbSyPqneoi+TlEQWer6M+zOTLfroKijt1AJZiF7kzr5tpiu5HgZ9K300Ho3GFRBcqs6oWnfynzXL3hY8Pl99RbYgQUBwNFrd0X71gThHpuvgy2HniUBHhvLS1r7E1SArU8hNrrSr9krrtjGtM9G8Ti56Li0if3KGR8dthGG6rFOBNWv4RG3HUMpPuslSbgEd0tlo2yYRQADqLIK/WD64b7B5zgxmYvyN2jkozJFQ1S0znxKxHJDBXRY0DK2r1yOuKFWM1+WVpKDnGmti4TMe6rE1Gdm2dTKJSePILPPr3z6hCIMEtBsvfn7Wwmw+SlG3NZVcAUqcARltyhjKiMTNb/r00m8YQtBj2Ry9qKhtuXCGEbsaGc2L9/2Jn4NHr1hwXWWiSXn1oyvCTKrp1OZWsT/dX9eGofnJ5V/k601FYQeL4T2xBu0yseKyszbLhNz3QBqpQNUdF2HIQnu2V5lAXj1N1jhWRbgqHViEp+PwFKjtnuJgqGtzdSA3+52JUVRBga1JnVboQt88eUIcUe+2KuXLf5AxWRJ2uHUIUoSWo/SJsBDbVJy+8ikLE/MBhRVkemo/pw/PY2LmSePSvuDsmBsHdN6UU6r/6YxvdehNlnOiRR8BqlV59iMjRBiv59YAQx1qVoPtBTVMI=
script:
- pytest --cmdopt=$CMDOPT
