language: python
sudo: required
dist: xenial
python:
- 3.7
install:
- pip install -e .
env:
  secure: 0OhzDUXCxG0E+By27T5Nzqhw8+dWRiTtr3ZZyk8NWiYDqJCf67vN2OxjprR0uyGngxBjJJG4Mr7zUGDAcwxoX2VcZXlIrrQKDf98VkuTTwl1XjXOQrmj32BI4wIB1FdpDkK97mpzAURId+hVOtT6W0jYaaHRGEkQAMmv6f9fFLHdKCUF30ofzASjsOS5ZdIMtygP5HEfIJpisH70eL5vnvBnsepEYdoskT8MZmKmFrh680Pub91Ba+ic4CR9fohr7EmA6xmYxBdPRy+A+k67ZQ/EQoK0vz2ZMeY/+gH8Qv+Wz3gfNdw4VwkTfC+GLGqIQlJjtC7/+sP7RG9vZzOOABAkRptUUpESH4xkrFaAHwE/MF1wgx2V2nAzGMW1WUsgu9sW+tLpgQbCX4BstIXbiOIv9eEnsSeUIX5Io0GQHQlMEKBqrzGfjnB5zZKgzmWiUgAqQjdNMLaud3675O9gLvvfFlD5Jsyrp/k5p1D9u9ssbOkQfZWnI8V9RnQBcioTvgCt4ITaQaMiegBW0lhnXvh/3qp0sGGza5yHed0BjeIe3DIb2fne5zzZvR4g7TiUXRkPMBQ1ojVcVfGB3+A5TOP6OARWrDA7Z4NHsHAfLNZOLUfiWN1OixnpTy/5s3xEKc7HpC4TKvV5csxfnBHZ8f32QHk58ZHOle70DOHoqE4=
script:
- pytest --cmdopt=$CMDOPT
