language: python
cache: pip
dist: xenial # currently needed for python >=3.7
python:
  - '3.7'
  - '3.8'
  - '3.9'
addons:
  mariadb: '10.3'
before_script:
  - mysql -u root -e 'CREATE DATABASE sc2monitor DEFAULT CHARACTER SET utf8 DEFAULT COLLATE utf8_general_ci;'
  - mysql -u root -e 'CREATE USER IF NOT EXISTS travis@localhost; GRANT ALL ON *.* TO travis@localhost;'
install:
  - 'pip install pip -U'
  - 'pip install -r test/requirements.txt -U'
  - 'pip install -e . -U'
script:
  - 'pytest -v --cov --cov-report xml --cov sc2monitor --cov-append --log-cli-level=INFO --apikey=$apikey --apisecret=$apisecret'
  - 'pytest -v --cov --cov-report xml --cov sc2monitor --cov-append --log-cli-level=INFO --apikey=$apikey --apisecret=$apisecret --protocol=mysql+pymysql --db=127.0.0.1 --user=travis'
after_success: codecov
deploy:
  provider: pypi
  user: "pressure"
  password: "$pypi"
  skip_existing: true
  on:
    distributions: "sdist bdist_wheel"
    branch: master
    condition: $TRAVIS_PYTHON_VERSION=3.8
